name: procurapet
description: "Projeto de um aplicativo para procurar pets"

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.0
  flutter_dotenv: ^6.0.0
  firebase_storage: ^13.0.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/procurapet.png
    - .env